import Head from "next/head";
import Header from "./../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <h1 className="text-4xl font-bold text-red-900 underline">
        Hello world!
      </h1>
    </>
  );
}
